version: '3.7'

services:
  web:
    build: web
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    build: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    env_file:
      - .env
  agent:
    build: agent
    ports:
    - "27015:27015"
    volumes:
    - "./data/OGP_User_Files:/home/ogp_agent/OGP_User_Files"
