version: '3.7'

services:
  web:
    build: .
    restart: always
    volumes:
    - "./config.inc.php:/app/includes/config.inc.php"
  mysql:
    build: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    env_file:
      - .env
