version: '3.7'

services:
  web:
    build: .
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    env_file:
      - .env
    volumes:
      - "./opengamepanel.sql:/docker-entrypoint-initdb.d/opengamepanel.sql"
      - "./data/mysql:/var/lib/mysql"
