version: '3.7'

services:
  web:
    image: henri9813/opengamepanel-web
    restart: always
    volumes:
    - "./web/config.inc.php:/app/includes/config.inc.php"
    depends_on:
      - mysql
  mysql:
    build: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    env_file:
      - .env
  agent:
    image: henri9813/opengamepanel-agent
